// Apartment hunt data — Fadi & Nomi
// Anchor: Credit Valley Hospital, 2200 Eglinton Ave W, Mississauga
// Move-in: July 2026
// Generated: 2026-04-27

const CVH = { lat: 43.5594410, lng: -79.7037121, name: "Credit Valley Hospital" };
const OLD_HOME = { lat: 43.6432, lng: -79.4006, name: "11 Charlotte St (old)" };

const APARTMENTS = [
  {
    id: "elora",
    name: "Elora (Minto)",
    address: "6515 Glen Erin Dr, Mississauga, L5N 8P9",
    zone: "Central Erin Mills (Meadowvale)",
    rent_1bed_low: 2225, rent_1bed_high: 2780,
    sqft_low: 511, sqft_high: 639,
    pets: "yes — on-site pet wash station (rare differentiator)",
    pet_status: "verified",
    drive_to_cvh_km: 6, drive_to_cvh_min_offpeak: 9, drive_to_cvh_min_peak: 12,
    drive_to_union_min_offpeak: 28,
    running: "Sawmill Valley + Culham Trail ~5 min south. 3-season elite, no winter maintenance.",
    transit: "MiWay bus to Erin Mills GO; ~50 min to Union via GO+TTC",
    promo: "Up to $5,000 off + free WiFi on select suites",
    red_flags: "Older 1980s tower with full reno; AC is ductless mini-split (not central); 1-bed sqft small for couple+dog",
    rating: "GOOD",
    listing_url: "https://www.mintoapartments.com/gta/Mississauga-apartment-rentals/Elora/main.html",
    lat: 43.5830211, lng: -79.7539141,
    pros: ["Pet wash station", "Full reno", "Closest to Sawmill running spine", "Free WiFi promo"],
    cons: ["Small sqft (511-639)", "Mini-split AC not central", "Older bones"],
    visual_note: "PHOTO CONFIRMS: gorgeous fully-renovated unit. White cabinets, light-wood plank floors, kitchen island, recessed lighting, light-filled. Premium feel for the price."
  },
  {
    id: "battleford_glen_erin",
    name: "Battleford & Glen Erin",
    address: "6599 Glen Erin Dr, Mississauga, L5N 2X3",
    zone: "Central Erin Mills (Meadowvale)",
    rent_1bed_low: 2149, rent_1bed_high: 2271,
    sqft_low: 620, sqft_high: 742,
    pets: "yes — dogs and cats explicitly OK",
    pet_status: "verified",
    drive_to_cvh_km: 6, drive_to_cvh_min_offpeak: 9, drive_to_cvh_min_peak: 12,
    drive_to_union_min_offpeak: 30,
    running: "Same Sawmill/Culham access as Elora. ~5 min south.",
    transit: "Bus to Erin Mills + Lisgar GO",
    promo: "2 months free rent (Morguard branding observed; current operator may be InterRent — verify)",
    red_flags: "InterRent corporate ratings 1.3-2/5 across multiple platforms (flooding, unresponsive). Verify operator.",
    rating: "FINE — verify operator",
    listing_url: "https://www.zumper.com/apartment-buildings/p322177/battleford-glen-erin-meadowvale-mississauga-on",
    lat: 43.5840974, lng: -79.7554141,
    pros: ["Bigger sqft than Elora at lower price", "Pool, BBQ, playground", "Pets explicitly OK"],
    cons: ["InterRent corporate concerns", "1970s-80s building"],
    visual_note: "Photos show a 1970s buff-brick tower; suite shots show parquet floors + sliding glass to balcony — older bones, not gut-renovated like Elora."
  },
  {
    id: "reid_drive",
    name: "Reid Drive Apartments (14 Skylark)",
    address: "10-14 Reid Dr, Mississauga, L5M 2A8",
    zone: "Streetsville",
    rent_1bed_low: 2170, rent_1bed_high: 2549,
    sqft_low: 716, sqft_high: 898,
    pets: "yes — dogs and cats OK, outdoor space for pets",
    pet_status: "verified",
    drive_to_cvh_km: 4, drive_to_cvh_min_offpeak: 9, drive_to_cvh_min_peak: 11,
    drive_to_union_min_offpeak: 43, // via Streetsville GO Milton line, slow
    running: "Riverwood Yellow+Red Loop (1,578 AllTrails reviews — most-reviewed in Mississauga). Culham Trail north access.",
    transit: "5 min walk to Streetsville GO (Milton line, less frequent)",
    promo: null,
    red_flags: "Surface lot only (no underground); Milton line GO has rush-only service",
    rating: "GOOD",
    listing_url: "https://www.zumper.com/apartment-buildings/p296363/reid-drive-apartments-at-14-skylark-apts-mississauga-on-l5m-2a8",
    lat: 43.5754891, lng: -79.7040106,
    pros: ["Largest 1-beds on shortlist (716-898 sqft)", "Gut-renovated kitchens (quartz waterfall, two-tone cabinets)", "Streetsville village + GO walkable"],
    cons: ["Milton line GO frequency", "Surface parking only"],
    visual_note: "Suite photos show recent gut reno: white quartz waterfall counters, two-tone cabinets (gloss white upper / espresso lower), full SS, light wide-plank LVP. Modern."
  },
  {
    id: "collegeway_2285",
    name: "2285 The Collegeway (Hazelview)",
    address: "2285 The Collegeway, Mississauga, L5L 2M3",
    zone: "Erin Mills (south)",
    rent_1bed_low: null, rent_1bed_high: null, // 1-bed waitlist; 2-bed $2,190 / 791 sqft
    rent_2bed: 2190,
    sqft_low: null, sqft_high: 791,
    pets: "yes — cats and dogs explicitly",
    pet_status: "verified",
    drive_to_cvh_km: 3.5, drive_to_cvh_min_offpeak: 6, drive_to_cvh_min_peak: 8,
    drive_to_union_min_offpeak: 35,
    running: "Credit River Valley + UTM Nature Trail ~10 min walk. Closest building to Sawmill spine.",
    transit: "Bus to Clarkson GO or Streetsville",
    promo: null,
    red_flags: "1-bed currently waitlist; call (289) 401-9832 immediately for July",
    rating: "GOOD — closest to CVH",
    listing_url: "https://www.hazelviewproperties.com/properties/2285-the-collegeway",
    lat: 43.5402711, lng: -79.6830518,
    pros: ["CLOSEST building to CVH (3.5 km)", "Hazelview confirmed pet-friendly", "Zumper Expert Rating 9.7/10"],
    cons: ["1-bed waitlist", "Older building"],
    visual_note: "Photo behind the Hazelview '2 months free' overlay shows grey sectional, modern coffee table, framed art — recently refreshed living room."
  },
  {
    id: "miracle_4900",
    name: "Miracle in Mississauga (condo)",
    address: "4900 Glen Erin Dr, Mississauga, L5M 7S2",
    zone: "Central Erin Mills",
    rent_1bed_low: 2150, rent_1bed_high: 2400,
    sqft_low: 600, sqft_high: 944,
    pets: "DEPENDS on condo declaration — 'pet-friendly' on listings but condo carve-out applies",
    pet_status: "verify-condo-rules",
    drive_to_cvh_km: 5, drive_to_cvh_min_offpeak: 8, drive_to_cvh_min_peak: 11,
    drive_to_union_min_offpeak: 28,
    running: "Glen Erin Trail / Sawmill access ~5 min",
    transit: "Bus to Erin Mills GO",
    promo: null,
    red_flags: "Condo — RTA s.14 does NOT protect you if declaration bans pets. Demand declaration before signing. Per-unit landlord variance.",
    rating: "FINE — pending condo declaration check",
    listing_url: "https://condos.ca/mississauga/miracle-in-mississauga-4900-glen-erin-dr",
    lat: 43.5535701, lng: -79.7110129,
    pros: ["Indoor pool, concierge, gym", "Multiple units active", "Built 2013 (newer)"],
    cons: ["Condo declaration risk", "Per-unit variance"]
  },
  {
    id: "arc_erin_mills",
    name: "Arc Erin Mills (Daniels)",
    address: "2520 Eglinton Ave W, Mississauga, L5M 0Y4",
    zone: "Central Erin Mills",
    rent_1bed_low: null, rent_1bed_high: null, rent_2bed: 2700,
    sqft_low: null, sqft_high: 946,
    pets: "yes — dogs/cats OK (verify condo declaration)",
    pet_status: "verify-condo-rules",
    drive_to_cvh_km: 2, drive_to_cvh_min_offpeak: 5, drive_to_cvh_min_peak: 7,
    drive_to_union_min_offpeak: 30,
    running: "Walking distance to Sawmill Valley + Glen Erin Trail",
    transit: "MiWay bus on Eglinton",
    promo: null,
    red_flags: "No 1-bed inventory currently; only 2-bed 946 sqft. Built 2019.",
    rating: "GOOD — but stretch budget for 2-bed",
    listing_url: "https://www.zumper.com/apartment-buildings/p406320/daniels-gateway-arc-erin-mills-central-erin-mills-mississauga-on",
    lat: 43.5582480, lng: -79.7074941,
    pros: ["LITERALLY ON EGLINTON 2 km from CVH", "Built 2019 (newest)", "Strata.ca: 'flawless management'"],
    cons: ["No 1-bed inventory", "Condo declaration risk"],
    visual_note: "Lobby photo: PREMIUM. Geometric perforated metal wall art, designer pendants, dark-grey sectionals, marble coffee table, floor-to-ceiling glass walls. Boutique-hotel feel."
  },
  {
    id: "dialogue",
    name: "Dialogue (BGO)",
    address: "4235 Confederation Pkwy, Mississauga, L5B 0E5",
    zone: "Square One / City Centre",
    rent_1bed_low: 2275, rent_1bed_high: 2460,
    sqft_low: null, sqft_high: null,
    pets: "yes — pet spa amenity",
    pet_status: "verified",
    drive_to_cvh_km: 9, drive_to_cvh_min_offpeak: 12, drive_to_cvh_min_peak: 25,
    drive_to_union_min_offpeak: 32,
    running: "Cooksville Creek Trail (~2 km usable). Burnhamthorpe Trail (winter-maintained 11 km) is your spine here.",
    transit: "MiWay City Centre Terminal hub; future Hurontario LRT (delayed to 2028)",
    promo: "2 months free + 1-year free WiFi",
    red_flags: "Hurontario LRT chaos through 2028 degrades north-south routes. Square One running fragmented. Brand new = no track record.",
    rating: "GOOD if amenities matter",
    listing_url: "https://www.rentdialogue.com/",
    lat: 43.5897825, lng: -79.6503031,
    pros: ["24/7 concierge, dog spa, smart home", "BGO institutional landlord", "2 mo free + free WiFi"],
    cons: ["LRT construction chaos", "Running is fragmented", "Higher base rent"],
    visual_note: "Premium look confirmed: light-wood quartz waterfall island, white kitchen, white-bouclé bar stools, track lighting. Most modern of the verified options."
  },
  {
    id: "lincoln_545",
    name: "Lincoln Towers — 545 The West Mall (Greenwin)",
    address: "545 The West Mall, Etobicoke, M9C 1G6",
    zone: "Etobicoke West Mall / Centennial",
    rent_1bed_low: 1845, rent_1bed_high: 2100,
    sqft_low: null, sqft_high: null,
    pets: "yes — cats and dogs",
    pet_status: "verified",
    drive_to_cvh_km: 16, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 35,
    drive_to_union_min_offpeak: 22,
    running: "Centennial Park (5 min walk) + Etobicoke Creek Trail. Markland Wood golf breaks creek continuity. Etobicoke Creek not maintained Nov-Apr.",
    transit: "MiWay 5/26 + 50 connecting to Kipling subway; bus to Mimico GO",
    promo: "1 month free",
    red_flags: "RentSafeTO 78/100 (acceptable; pest log good). Older building. AM peak 28-40 min to CVH (Tier 3).",
    rating: "GOOD VALUE",
    listing_url: "https://www.greenwin.ca/properties/545-the-west-mall",
    lat: 43.6516887, lng: -79.5695913,
    pros: ["CHEAPEST verified pet-friendly 1-bed ($1,845)", "Heat + water included", "1 month free", "Walking distance to Centennial Park"],
    cons: ["Older building (1970s)", "Tier 3 commute", "Etobicoke Creek not winter-maintained"],
    visual_note: "Behind the '1 month free' overlay: large windows, parquet hardwood floors, baseboard heaters. Empty unit shot — older bones, not renovated. Tour in person."
  },
  {
    id: "mill_road_340",
    name: "340 Mill Road (Park Property)",
    address: "340 Mill Rd, Etobicoke, M9C 1Y8",
    zone: "Markland Wood",
    rent_1bed_low: 2149, rent_1bed_high: 2300,
    sqft_low: null, sqft_high: null,
    pets: "yes (size/breed unverified)",
    pet_status: "verify-specifics",
    drive_to_cvh_km: 14, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 32,
    drive_to_union_min_offpeak: 25,
    running: "Centennial Park 1.5 km north. Etobicoke Creek Trail access.",
    transit: "Bus to Kipling subway",
    promo: "1 month free + $1,000",
    red_flags: "One Yelp review flagged 'rough crowd, screen tenants better'",
    rating: "FINE",
    listing_url: "https://www.parkproperty.ca/apartments/340-mill-road",
    lat: 43.6397985, lng: -79.5855821,
    pros: ["1 month free + $1,000 cash", "Newly renovated", "Co-working + Wi-Fi lounge"],
    cons: ["Yelp tenant complaint", "Tier 3 commute"],
    visual_note: "Exterior is utilitarian 16-17 storey concrete tower with white balconies — looks 1970s-80s, less aesthetically pleasing than Erin Mills options."
  },
  {
    id: "mimico_estates",
    name: "Mimico Estates (CAPREIT)",
    address: "2527 Lake Shore Blvd W, Etobicoke, M8V 1E5",
    zone: "Mimico / Lake Shore",
    rent_1bed_low: 1830, rent_1bed_high: 2100,
    rent_studio: 1450, rent_2bed: 2495,
    sqft_low: 788, sqft_high: 900,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 22, drive_to_cvh_min_offpeak: 26, drive_to_cvh_min_peak: 50,
    drive_to_union_min_offpeak: 17, drive_to_union_min_via_go: 17, // Mimico GO to Union
    running: "MARTIN GOODMAN TRAIL — only year-round-cleared running surface in west GTA. Doorstep 30km long runs east to downtown.",
    transit: "Mimico GO 5 min walk; 17 min to Union",
    promo: "1.5 months free",
    red_flags: "AM peak 35-50 min to CVH. No central AC, window units only. No balconies. 1950s-60s low-rise.",
    rating: "STRETCH — best running, worst commute",
    listing_url: "https://www.zumper.com/apartment-buildings/p288791/mimico-estates-mimico-toronto-on",
    lat: 43.6102238, lng: -79.4890189,
    pros: ["788 sqft 1-bed (largest on list) for $1,830", "Martin Goodman Trail = year-round bare pavement", "Mimico GO 17 min to Union", "1.5 months free"],
    cons: ["35-50 min AM peak to CVH", "No central AC, no balconies", "Old building"],
    visual_note: "SURPRISING CHARM: courtyard photo shows mid-century buff-brick low-rise around manicured topiary garden + small fountain. Quiet, established, almost institutional/landscaped. Window AC units visible (no central). Unique vibe — felt more like a college quad than a rental."
  },
  {
    id: "walden_circle",
    name: "Walden Circle",
    address: "1201 Walden Cir, Mississauga, L5J 4M9",
    zone: "Clarkson",
    rent_1bed_low: 1710, rent_1bed_high: 1971,
    sqft_low: null, sqft_high: null,
    pets: "CONFLICTING — listings disagree; verify directly",
    pet_status: "conflicting",
    drive_to_cvh_km: 9, drive_to_cvh_min_offpeak: 14, drive_to_cvh_min_peak: 19,
    drive_to_union_min_offpeak: 32,
    running: "Mississauga Waterfront Trail 16.9 km (NOT winter maintained). Rattray Marsh (no bikes, dog-friendly).",
    transit: "3-MIN WALK TO CLARKSON GO. ~32 min to Union.",
    promo: null,
    red_flags: "Pet policy conflicts across listing sites. Confirm in writing before viewing.",
    rating: "POTENTIAL — pet TBD",
    listing_url: "https://rentals.ca/mississauga/1201-walden-circle",
    lat: 43.5134823, lng: -79.6320598,
    pros: ["CHEAPEST 1-bed ($1,710)", "3 min walk to Clarkson GO", "Pool, fitness, squash, tennis"],
    cons: ["Pet policy unverified", "No winter trail maintenance on waterfront"],
    visual_note: "Photo shows BIG corner-window unit with skyline view, fresh white walls, light-wood floors, white SS kitchen. Recently renovated — better than expected for the price. Strong upside if pets work out."
  },
  {
    id: "lakewood_1257",
    name: "Lakewood Apartments I (1257 Lakeshore E)",
    address: "1257 Lakeshore Rd E, Mississauga, L5E 1H1",
    zone: "Lakeview Mississauga",
    rent_1bed_low: 1900, rent_1bed_high: 2200,
    sqft_low: null, sqft_high: null,
    pets: "yes",
    pet_status: "verified",
    drive_to_cvh_km: 14, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 28,
    drive_to_union_min_offpeak: 26, // via Long Branch GO
    running: "Lakefront Promenade Trail; quiet residential streets; Mississauga Waterfront Trail east-west spine.",
    transit: "Bus to Long Branch GO (~22 min to Union via GO)",
    promo: null,
    red_flags: "Older building; Lakeview is industrial-adjacent in spots — verify exact location",
    rating: "POTENTIAL",
    listing_url: "https://www.zumper.com/apartment-buildings/p219250/1257-lakeshore-road-east-lakeview-mississauga-on",
    lat: 43.5819835, lng: -79.5535542,
    pros: ["Pet-friendly confirmed", "Waterfront access"],
    cons: ["Industrial adjacency in spots"]
  },
  {
    id: "forty_second_45",
    name: "45 Forty Second St (Greenwin)",
    address: "45 Forty Second St, Etobicoke, M8V 0E1",
    zone: "Long Branch / New Toronto",
    rent_1bed_low: 2249, rent_1bed_high: 2400,
    sqft_low: null, sqft_high: null,
    pets: "yes — explicitly pet-friendly",
    pet_status: "verified",
    drive_to_cvh_km: 19, drive_to_cvh_min_offpeak: 23, drive_to_cvh_min_peak: 42,
    drive_to_union_min_offpeak: 22,
    running: "Marie Curtis Park / Etobicoke Creek mouth + Martin Goodman waterfront — year-round cleared. Doorstep to lake.",
    transit: "Long Branch GO 5 min walk; ~22 min to Union",
    promo: null,
    red_flags: "Etobicoke-Lakeshore RentSafeTO area average 92/100 (good). No specific complaints found.",
    rating: "GOOD — Toronto vibe + waterfront",
    listing_url: "https://www.greenwin.ca/students/45-forty-second-st",
    lat: 43.5882491, lng: -79.5427490,
    pros: ["Across from Marie Curtis Park", "5 min walk to Long Branch GO (22 min Union)", "Martin Goodman waterfront access", "Brand new red-brick build with retail at base"],
    cons: ["Tier 4 commute to CVH (35-50 min peak)", "Higher rent than CEM"],
    visual_note: "Photo confirms: brand-new 3-storey red-brick mixed-use building with retail at street, white-trim windows, modern facade. Solid build."
  },
  // ===== TORONTO-CLOSE TIER (Humber Bay / Mimico / Stonegate) =====
  {
    id: "vita_on_the_lake",
    name: "Vita on the Lake (condo)",
    address: "70 Annie Craig Dr, Toronto, M8V 0G2",
    zone: "Humber Bay Shores",
    rent_1bed_low: 1900, rent_1bed_high: 2400,
    sqft_low: 524, sqft_high: 700,
    pets: "yes — Mattamy condo, generally pet-friendly; size limits per board (verify per unit)",
    pet_status: "verify-condo-rules",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 50,
    drive_to_union_min_offpeak: 25, drive_to_union_min_via_go: 14,
    running: "DOORSTEP to Humber Bay Park East/West, Sheldon Lookout, Martin Goodman Trail (year-round cleared). Best running base in west GTA — closest match to old Harbourfront life.",
    transit: "501 streetcar 5 min walk; Mimico GO 12 min walk; bike to Union ~25 min on Waterfront Trail",
    promo: null,
    red_flags: "Individual landlord = pet rules vary by unit; verify dog size with listing agent. 1+12 = 13 active listings spread $1,900-$2,400.",
    rating: "STRETCH — best running, worst commute",
    listing_url: "https://condos.ca/toronto/vita-on-the-lake-70-annie-craig-dr",
    lat: 43.6232, lng: -79.4805,
    pros: ["Doorstep Humber Bay Park + Martin Goodman", "New 2021 building", "Pool, gym, concierge", "Walking distance to Mimico GO"],
    cons: ["Per-unit landlord variance", "AM peak 40-55min to CVH (Tier 4)"]
  },
  {
    id: "lago_waterfront",
    name: "Lago at the Waterfront (condo)",
    address: "56 Annie Craig Dr, Toronto, M8V 0E1",
    zone: "Humber Bay Shores",
    rent_1bed_low: 2000, rent_1bed_high: 2500,
    sqft_low: 500, sqft_high: 700,
    pets: "yes — building has on-site PET WASHING STATION",
    pet_status: "verify-condo-rules",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 50,
    drive_to_union_min_offpeak: 25,
    running: "Same waterfront access as Vita; pet washing station on-site after muddy lakeside runs.",
    transit: "501 streetcar 5 min walk; Mimico GO 12 min walk",
    promo: null,
    red_flags: "Condo individual landlords; weight limits possible despite building rep",
    rating: "STRETCH — same as Vita with pet wash bonus",
    listing_url: "https://condos.ca/toronto/lago-at-the-waterfront-56-annie-craig-dr",
    lat: 43.6232, lng: -79.4810,
    pros: ["On-site pet washing station (rare)", "2017 Mattamy build", "Indoor pool, hot tub, sauna, theatre", "Same Martin Goodman doorstep as Vita"],
    cons: ["Per-unit variance", "Tier 4 CVH commute"]
  },
  {
    id: "eau_du_soleil",
    name: "Eau du Soleil (Sky/Water Tower)",
    address: "20 & 30 Shore Breeze Dr, Toronto, M8V 0H1",
    zone: "Humber Bay Shores",
    rent_1bed_low: 2300, rent_1bed_high: 2700,
    sqft_low: 485, sqft_high: 700,
    pets: "yes — LARGE PETS ACCEPTED (one of three Humber Bay buildings noted as 'welcoming pets of all sizes')",
    pet_status: "verified-large-pets",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 50,
    drive_to_union_min_offpeak: 25,
    running: "Best running base in Toronto-close list — directly on Humber Bay Park West loop, Sheldon Lookout, paved + grass options, lake views the whole way.",
    transit: "Mimico GO 11 min walk; 501 streetcar 4 min walk",
    promo: null,
    red_flags: "Premium tier — rents creep above budget. Tenant fee may apply per listing agent.",
    rating: "STRETCH — best for big dogs",
    listing_url: "https://condos.ca/toronto/water-tower-at-eau-du-soleil-20-shore-breeze-drive-20-shore-breeze-dr",
    lat: 43.6210, lng: -79.4830,
    pros: ["LARGE PETS WELCOMED (rare)", "Saltwater pool, theatre, party rooms, guest suites", "Tallest residential tower west of downtown", "Doorstep Humber Bay Park West"],
    cons: ["Top of budget", "Tier 4 commute", "Per-unit variance"],
    visual_note: "PHOTOS CONFIRM: STUNNING. Twin glass towers reflected in Lake Ontario at sunset. Suite-level shot shows downtown Toronto skyline (CN Tower visible) directly across the lake. Best lake-and-skyline view of any option in this list. The closest you'll get to that 11 Charlotte Harbourfront feeling — except you're looking AT downtown across the lake instead of being in it."
  },
  {
    id: "promenade_2301",
    name: "Promenade Apartments",
    address: "2301 Lake Shore Blvd W, Toronto, M8V 1A7",
    zone: "Mimico (Lake Shore at Park Lawn)",
    rent_1bed_low: 1895, rent_1bed_high: 2050,
    sqft_low: 573, sqft_high: 573,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 45,
    drive_to_union_min_offpeak: 17, drive_to_union_min_via_go: 17,
    running: "Waterfront Trail across the street; Humber Bay Butterfly Habitat 1km; eastbound to Sunnyside or west to Mimico Creek.",
    transit: "501 streetcar at door; Mimico GO ~10 min walk; Union ~17 min via GO",
    promo: "$1,000 move-in bonus (select suites)",
    red_flags: "Smaller 1-bed (573 sqft); dual-glazed windows over Lake Shore can be loud",
    rating: "POTENTIAL — pet-verified waterfront",
    listing_url: "https://www.zumper.com/apartment-buildings/p219253/promenade-apartments-mimico-toronto-on",
    lat: 43.6105, lng: -79.4885,
    pros: ["Sub-$1,900 1-bed waterfront", "$1,000 move-in bonus", "Pet-verified", "501 streetcar at door"],
    cons: ["Small 573 sqft", "Lake Shore traffic noise"],
    visual_note: "PHOTO CONFIRMS: nicely renovated bedroom — parquet floors, fresh white walls, framed art, modern bedside lamp, plant. Premium tasteful staging. Window view shows architectural building (urban context)."
  },
  {
    id: "landmark_2493",
    name: "Landmark Apartments",
    address: "2493 Lake Shore Blvd W, Toronto, M8V 1C7",
    zone: "Mimico",
    rent_1bed_low: 1995, rent_1bed_high: 2255,
    sqft_low: 620, sqft_high: 620,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 48,
    drive_to_union_min_offpeak: 14, drive_to_union_min_via_go: 14,
    running: "200m to Waterfront Trail; Humber Bay Park West for tempo loops; safe for late-night runs after ER shifts.",
    transit: "Mimico GO 6 min walk; 501 streetcar at door; Union ~14 min by GO",
    promo: "EV charging on-site",
    red_flags: "Homestead corporate pattern of complaints (deposits, hot water, pest issues across portfolio). VERIFY this specific building tour carefully.",
    rating: "CAUTION — corporate red flag",
    listing_url: "https://www.zumper.com/apartment-buildings/p219251/landmark-apartments-mimico-toronto-on",
    lat: 43.6118, lng: -79.4960,
    pros: ["620 sqft for $1,995", "Mimico GO 6 min", "501 streetcar at door"],
    cons: ["Homestead corporate complaints", "Older purpose-built"],
    visual_note: "Photo: Beautifully renovated galley kitchen — white shaker cabinets, subway tile, dark quartz, SS appliances, breakfast nook with bar stools. Premium reno. Visual contradicts Homestead corporate complaints — but that's marketing photography. Tour in person."
  },
  {
    id: "lake_shore_155",
    name: "155 Lake Shore (InterRent)",
    address: "155 Lake Cres, Etobicoke (Mimico)",
    zone: "Mimico",
    rent_1bed_low: 2049, rent_1bed_high: 2200,
    sqft_low: 658, sqft_high: 658,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 48,
    drive_to_union_min_offpeak: 14,
    running: "Lakefront block — direct access to Waterfront Trail; quieter side street vs Lake Shore frontage buildings.",
    transit: "Mimico GO ~7 min walk; 501 streetcar 2 min walk",
    promo: "24/7 emergency, controlled entrance",
    red_flags: "Smaller InterRent portfolio building — InterRent corporate complaints exist. Verify pet size at application.",
    rating: "GOOD VALUE — beautiful unit",
    listing_url: "https://www.zumper.com/apartment-buildings/p1064024/155-lake-shore-mimico-toronto-on",
    lat: 43.6105, lng: -79.4900,
    pros: ["Lakefront block — quieter side street vs Lake Shore frontage", "Mimico GO 7 min", "501 streetcar 2 min", "658 sqft for $2,049"],
    cons: ["Smaller InterRent building", "Verify dog size"],
    visual_note: "STAR FINDING: Photo shows GORGEOUS modern unit. Full white shaker kitchen, quartz waterfall island with dark wood base, SS appliances, IN-SUITE STACKED W/D, light wide-plank floors, tons of pot lights. Premium reno — visually competitive with the Erin Mills options at similar price."
  },
  {
    id: "shoreline_towers",
    name: "Shoreline Towers (Briarlane)",
    address: "2313-2323 Lake Shore Blvd W, Toronto, M8V 1B8",
    zone: "Mimico",
    rent_1bed_low: 1797, rent_1bed_high: 1997,
    sqft_low: 616, sqft_high: 616,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 22, drive_to_cvh_min_peak: 45,
    drive_to_union_min_offpeak: 17,
    running: "Direct Waterfront Trail access; same trail network as Promenade/Landmark.",
    transit: "501 streetcar at door; Mimico GO 8 min walk",
    promo: "1 month FREE on 12-month lease",
    red_flags: "Older twin-tower stock; verify renovation level on each suite",
    rating: "GOOD VALUE — verified pet + cheapest waterfront",
    listing_url: "https://www.zumper.com/apartment-buildings/p1282006/2313-2323-lake-shore-boulevard-west-mimico-toronto-on",
    lat: 43.6105, lng: -79.4895,
    pros: ["$1,797 1-bed (cheapest waterfront verified pet)", "1 month free", "Gym + EV charging", "501 + Mimico GO"],
    cons: ["1970s twin towers, verify reno", "Briarlane mgmt — limited public reviews"],
    visual_note: "Photo is a Briarlane 'ONE MONTH RENT FREE' promo card with stock 'moving boxes' image — no real building or unit shot extractable. Demand more photos before viewing."
  },
  {
    id: "park_lawn_285",
    name: "285 Park Lawn Road",
    address: "285 Park Lawn Rd, Toronto, M8Y 3J7",
    zone: "Stonegate",
    rent_1bed_low: 1500, rent_1bed_high: 1795,
    sqft_low: 650, sqft_high: 650,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 13, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 38,
    drive_to_union_min_offpeak: 28,
    running: "Mimico Creek 4 min walk; can run south to lake (3 km) or north to South Humber Park.",
    transit: "66 Prince Edward bus to Old Mill subway (~20 min total to Bloor line); future Park Lawn GO will be steps away",
    promo: null,
    red_flags: "Older mid-rise; 9.4/10 Zumper rating but verify suite renovation. Future GO not open yet.",
    rating: "GOOD VALUE — cheapest verified Toronto pet 1-bed",
    listing_url: "https://www.zumper.com/apartment-buildings/p794731/285-park-lawn-road-stonegate-queensway-toronto-on",
    lat: 43.6360, lng: -79.4890,
    pros: ["$1,500-$1,795 1-bed 650 sqft (CHEAPEST Toronto-side verified pet)", "Stainless appliances", "Future Park Lawn GO at door (planned)", "Internet ready"],
    cons: ["Currently bus-dependent for subway", "No streetcar at door"],
    visual_note: "Behind '2 MONTHS RENT FREE May 1 2026' promo: white kitchen visible — SS fridge, white cabinets, light-wood floors, framed art. Modern renovation."
  },
  {
    id: "newholm_8",
    name: "8 Newholm Road",
    address: "8 Newholm Rd, Toronto, M8Y 3M4",
    zone: "Stonegate",
    rent_1bed_low: 1795, rent_1bed_high: 1900,
    sqft_low: null, sqft_high: null,
    pets: "yes — dogs and cats OK",
    pet_status: "verified",
    drive_to_cvh_km: 14, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 38,
    drive_to_union_min_offpeak: 28,
    running: "Mimico Creek trail 6 min walk; quiet residential streets for warm-up; Stonegate ravine.",
    transit: "66 bus to Old Mill subway; Park Lawn GO future (200 m)",
    promo: null,
    red_flags: "No transit at door currently; bus-dependent until Park Lawn GO opens",
    rating: "GOOD VALUE — renovated + cheap",
    listing_url: "https://www.zumper.com/apartment-buildings/p883469/8-newholm-road-stonegate-queensway-toronto-on",
    lat: 43.6320, lng: -79.4920,
    pros: ["Renovated units (stone counters, SS appliances)", "Heat/water included", "$1,795", "Future Park Lawn GO 200m"],
    cons: ["Bus-dependent for subway", "Stonegate suburban feel"],
    visual_note: "Photo behind '2 MONTHS RENT FREE May 1' overlay: white kitchen — SS fridge, white cabinets, light-wood floors, framed art. Sister property to 285 Park Lawn (same renovation template)."
  },
  {
    id: "markwood_4365",
    name: "The Markwood (Sterling Karamar)",
    address: "4365 Bloor St W, Etobicoke, M9C 0E2",
    zone: "Markland Wood / Bloor West edge",
    rent_1bed_low: 2253, rent_1bed_high: 2500,
    sqft_low: 483, sqft_high: 1003,
    pets: "yes — Dogs/Cats OK; ON-SITE DOG RUN",
    pet_status: "verified",
    drive_to_cvh_km: 7, drive_to_cvh_min_offpeak: 10, drive_to_cvh_min_peak: 22,
    drive_to_union_min_offpeak: 40,
    running: "Etobicoke Creek trail at building doorstep — paved + dirt, runs all the way to Lake Ontario (12 km south to Marie Curtis); Centennial Park 1.5 km.",
    transit: "49 Bloor bus to Kipling subway (~10 min); Kipling subway 4.5 km; Union ~40 min total",
    promo: "2 months FREE on 14-month lease + 3 months FREE parking + 6 months FREE locker",
    red_flags: "NEW 2024 build (Sterling Karamar). NOT to be confused with 240 Markland Drive (also Sterling Karamar — on AVOID list). Suburban feel.",
    rating: "GOOD — best CVH commute Toronto-side",
    listing_url: "https://www.zumper.com/apartment-buildings/p1333582/the-markwood-toronto-on",
    lat: 43.6360, lng: -79.5825,
    pros: ["SHORTEST CVH commute Toronto-side (~7 km, ~10 min)", "ON-SITE DOG RUN", "Aggressive promo (2 mo free + 3 mo parking + 6 mo locker)", "New 2024 build", "Etobicoke Creek doorstep"],
    cons: ["Bus-and-subway transit (~40 min Union)", "Suburban Markland Wood location", "Sterling Karamar mgmt mixed rep"],
    visual_note: "Photo behind Sterling Karamar promo overlay shows new 2024 unit — quartz counters, white cabinets, light-wood plank floors, white-trim. Genuine new build. NOT to be confused with 240 Markland (Sterling Karamar AVOID building)."
  },
  {
    id: "station_place_5249",
    name: "Station Place (5249 Dundas, Centurion)",
    address: "5249 Dundas St W, Etobicoke, M9B 1A5",
    zone: "Kipling subway core",
    rent_1bed_low: 2085, rent_1bed_high: 2275,
    sqft_low: null, sqft_high: null,
    pets: "yes — outdoor pet run + wash station on-site",
    pet_status: "verified",
    drive_to_cvh_km: 9, drive_to_cvh_min_offpeak: 12, drive_to_cvh_min_peak: 25,
    drive_to_union_min_offpeak: 16, drive_to_union_min_via_go: 16,
    running: "Mimico Creek trail 5 min walk; James Gardens / Humber River trail accessible via Bloor; not lakefront but trail-rich.",
    transit: "Kipling subway + Kipling GO + GO bus terminal 5 min walk = BEST TRANSIT BASE in dataset",
    promo: "2 months FREE on 12-month lease",
    red_flags: "Currently lists Apr/May 2026 availability; July 2026 will need new query.",
    rating: "GOOD — best transit base",
    listing_url: "https://www.cpliving.com/apartments/station-place",
    lat: 43.6370, lng: -79.5375,
    pros: ["BEST TRANSIT (Kipling subway + GO + bus terminal at door)", "Outdoor pet run + wash station", "On-site Farm Boy grocery", "New 2021 build", "In-suite W/D + outdoor infinity pool"],
    cons: ["Not lakefront", "Need to re-query July availability"]
  },
  {
    id: "james_90",
    name: "90 James / 25 Villa Rd (Greenwin)",
    address: "90 James St, Etobicoke, M8W 1L6",
    zone: "New Toronto",
    rent_1bed_low: 1799, rent_1bed_high: 1900,
    sqft_low: 487, sqft_high: 487,
    pets: "yes — dogs and cats OK; 'small pets' noted",
    pet_status: "verify-specifics",
    drive_to_cvh_km: 14, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 35,
    drive_to_union_min_offpeak: 26,
    running: "Colonel Samuel Smith Park 5 min walk — best dog/run park in west GTA; no traffic interference for 6+ km.",
    transit: "501 streetcar at door; Mimico GO 12 min walk",
    promo: "Heat included",
    red_flags: "Small footprint (487 sqft) — tight for two + dog. 'Small pets' caveat — verify large dog OK.",
    rating: "POTENTIAL — verify dog size",
    listing_url: "https://www.zumper.com/apartment-buildings/p1087251/90-92-james-st-25-villa-rd-long-branch-toronto-on",
    lat: 43.5995, lng: -79.5170,
    pros: ["$1,799 1-bed", "Heat included", "Col. Sam Smith Park 5 min (best dog park west GTA)", "501 streetcar at door"],
    cons: ["Only 487 sqft", "'Small pets' note may exclude large dogs"],
    visual_note: "Photo behind Greenwin '1 month free' overlay shows charming yellow-brick walk-up courtyard — looks like a 3-storey 1950s low-rise. Quiet residential vibe, more village than tower."
  },
  {
    id: "lakeshore_760",
    name: "760 Lakeshore Rd E",
    address: "760 Lakeshore Rd E, Mississauga, L5G 1J5",
    zone: "Lakeview Mississauga",
    rent_1bed_low: 1950, rent_1bed_high: 2200,
    sqft_low: null, sqft_high: null,
    pets: "yes",
    pet_status: "verified",
    drive_to_cvh_km: 13, drive_to_cvh_min_offpeak: 17, drive_to_cvh_min_peak: 26,
    drive_to_union_min_offpeak: 28, // via Long Branch GO
    running: "DOORSTEP LAKESHORE — sand beach + Mississauga Waterfront Trail east-west; bus to Marie Curtis. Beach photo confirms direct lake access.",
    transit: "Bus to Long Branch GO (~28 min Union via GO)",
    promo: null,
    red_flags: "Older building; Lakeview transitioning area",
    rating: "POTENTIAL — beach lifestyle + middle-distance CVH",
    listing_url: "https://rentals.ca/mississauga/760-lakeshore-rd-e",
    lat: 43.5640, lng: -79.5468,
    pros: ["Direct beach access (photo confirms)", "Pet-friendly", "Middle-distance CVH (~17 min off-peak)", "Quiet waterfront vibe"],
    cons: ["Lakeview is gentrifying — patchy nearby retail", "No GO walking distance"],
    visual_note: "Photo from beach is the actual lakeshore at the building's south side. Sandy, quiet, bench-and-pier vibe — better than expected for the price."
  },
];

// ===== ADDITIONAL ZONES (Cooksville, Applewood, Sheridan, Lorne Park) =====
APARTMENTS.push(
  {
    id: "applewood_on_park",
    name: "Applewood on the Park (QuadReal)",
    address: "1177 Bloor St E, Mississauga, L4Y 2N7",
    zone: "Applewood",
    rent_1bed_low: 2320, rent_1bed_high: 2500,
    sqft_low: null, sqft_high: null,
    pets: "yes — cats and dogs", pet_status: "verified",
    drive_to_cvh_km: 16, drive_to_cvh_min_offpeak: 18, drive_to_cvh_min_peak: 32,
    drive_to_union_min_offpeak: 24,
    running: "Applewood Trail (winter-maintained!) + Etobicoke Creek access. Garnetwood Park.",
    transit: "MiWay 24 to Dixie GO (~10 min); Union ~28 min via GO",
    promo: "1 month free for eligible applicants",
    red_flags: null,
    rating: "GOOD",
    listing_url: "https://quadrealresidential.com/mississauga/applewood-on-the-park/",
    lat: 43.6020, lng: -79.5995,
    pros: ["Newer QuadReal management", "Applewood Trail winter-maintained", "1 month free", "EV charging + pool"],
    cons: ["Tier 3 commute to CVH", "Eastern Mississauga not as scenic"]
  },
  {
    id: "sheridan_crossing",
    name: "Sheridan Crossing",
    address: "2225 Erin Mills Pkwy, Mississauga, L5K 1T9",
    zone: "Sheridan",
    rent_1bed_low: 2088, rent_1bed_high: 2350,
    sqft_low: null, sqft_high: null,
    pets: "yes — verify breed/size", pet_status: "verify-specifics",
    drive_to_cvh_km: 6, drive_to_cvh_min_offpeak: 9, drive_to_cvh_min_peak: 15,
    drive_to_union_min_offpeak: 32,
    running: "Sherwood Forrest area + nearby trails; ~2km to Erindale Park / Culham network.",
    transit: "Bus to Clarkson GO; ~32 min Union",
    promo: "1 mo free on 13-mo + 6 mo free parking; or 2 mo free on 14-mo lease",
    red_flags: null,
    rating: "GOOD — new build close to CVH",
    listing_url: "https://www.rentfaster.ca/on/mississauga/rentals/apartment/1-bedroom/pet-friendly/548833",
    lat: 43.5350, lng: -79.6480,
    pros: ["NEW 17-storey build", "Aggressive promo (1 mo free + 6 mo parking)", "Tier 1 CVH commute", "Open-concept SS kitchen, in-suite W/D"],
    cons: ["No GO walking distance"]
  },
  {
    id: "sheridan_manor",
    name: "The Sheridan Manor",
    address: "2095 Roche Court, Mississauga, L5K 2C5",
    zone: "Sheridan",
    rent_1bed_low: 2099, rent_1bed_high: 2300,
    sqft_low: null, sqft_high: null,
    pets: "yes — RTA s.14 protected (purpose-built rental)", pet_status: "verified",
    drive_to_cvh_km: 7, drive_to_cvh_min_offpeak: 11, drive_to_cvh_min_peak: 17,
    drive_to_union_min_offpeak: 32,
    running: "Sherwood Forrest + waterfront via short drive. Lornewood Park nearby.",
    transit: "Bus to Clarkson GO",
    promo: "1 month free on 13-month lease",
    red_flags: "InterRent corporate concerns possibly apply — verify operator",
    rating: "FINE",
    listing_url: "https://www.apartmenthomeliving.com/apartment-finder/The-Sheridan-Manor-Mississauga-ON-20075316",
    lat: 43.5270, lng: -79.6370,
    pros: ["Steps from waterfront/parks", "1 month free", "Tier 1 CVH commute"],
    cons: ["Older building"]
  },
  {
    id: "embassy_99_agnes",
    name: "Embassy Apartments",
    address: "99 Agnes Street, Mississauga, L5B 0E2",
    zone: "Cooksville",
    rent_1bed_low: 1850, rent_1bed_high: 2150,
    sqft_low: null, sqft_high: null,
    pets: "yes — cats and dogs", pet_status: "verified",
    drive_to_cvh_km: 8, drive_to_cvh_min_offpeak: 12, drive_to_cvh_min_peak: 25,
    drive_to_union_min_offpeak: 28,
    running: "Cooksville Creek Trail + Burnhamthorpe Trail (winter-maintained!) accessible.",
    transit: "Cooksville GO 12 min walk; Hurontario LRT future stop",
    promo: null,
    red_flags: "Hurontario LRT construction chaos through 2028",
    rating: "POTENTIAL",
    listing_url: "https://www.zumper.com/apartments-for-rent/mississauga-on/cooksville",
    lat: 43.5797, lng: -79.6090,
    pros: ["Pool + garage parking + concierge-style amenities", "Cooksville GO 12 min", "Burnhamthorpe winter trail"],
    cons: ["LRT construction noise/disruption through 2028"]
  },
  {
    id: "sherobee_2170",
    name: "2170 Sherobee Rd",
    address: "2170 Sherobee Rd, Mississauga, L5A 3J9",
    zone: "Cooksville",
    rent_1bed_low: 1900, rent_1bed_high: 2100,
    sqft_low: null, sqft_high: null,
    pets: "yes — cats and dogs", pet_status: "verified",
    drive_to_cvh_km: 9, drive_to_cvh_min_offpeak: 13, drive_to_cvh_min_peak: 25,
    drive_to_union_min_offpeak: 28,
    running: "Cooksville Creek 5 min walk; Burnhamthorpe Trail spine.",
    transit: "Cooksville GO 8 min walk",
    promo: null,
    red_flags: null,
    rating: "POTENTIAL",
    listing_url: "https://www.zumper.com/apartments-for-rent/mississauga-on/cooksville",
    lat: 43.5829, lng: -79.6147,
    pros: ["Pool + fitness", "Cooksville GO walkable", "Bus + future LRT"],
    cons: ["LRT chaos until 2028"]
  },
  {
    id: "dixie_square_1750",
    name: "Dixie Square Apartments",
    address: "1750 Bloor Street E, Mississauga, L4X 0E5",
    zone: "Applewood (Dixie)",
    rent_1bed_low: 1950, rent_1bed_high: 2200,
    sqft_low: null, sqft_high: null,
    pets: "yes — verify policy", pet_status: "verify-specifics",
    drive_to_cvh_km: 17, drive_to_cvh_min_offpeak: 19, drive_to_cvh_min_peak: 35,
    drive_to_union_min_offpeak: 26,
    running: "Applewood Trail + Etobicoke Creek; Garnetwood Park.",
    transit: "Dixie GO 8 min walk",
    promo: null,
    red_flags: null,
    rating: "POTENTIAL",
    listing_url: "https://www.zillow.com/applewood-mississauga-on/apartments/",
    lat: 43.6155, lng: -79.5990,
    pros: ["Dixie GO walkable", "Eastern Mississauga value"],
    cons: ["Tier 3 CVH commute", "Less polished area"]
  },
  {
    id: "1011_lorne_park",
    name: "1011 Lorne Park Rd",
    address: "1011 Lorne Park Rd, Mississauga, L5H 2Z9",
    zone: "Lorne Park",
    rent_1bed_low: 1891, rent_1bed_high: 2200,
    sqft_low: null, sqft_high: null,
    pets: "yes — verify breed/size", pet_status: "verify-specifics",
    drive_to_cvh_km: 9, drive_to_cvh_min_offpeak: 13, drive_to_cvh_min_peak: 22,
    drive_to_union_min_offpeak: 30,
    running: "Lorne Park Estates + Rattray Marsh (no bikes!). Jack Darling off-leash dog park 5 min.",
    transit: "Bus to Clarkson GO 12 min",
    promo: null,
    red_flags: "Older small building",
    rating: "POTENTIAL",
    listing_url: "https://apartments.com/1011-lorne-park-rd-mississauga-on/zsfbt9x",
    lat: 43.5305, lng: -79.6260,
    pros: ["Lorne Park is upscale residential", "Best dog park access (Jack Darling)", "Tier 2 CVH"],
    cons: ["Older building", "Limited transit"]
  },
);

// AVOID list — documented red flags
const AVOID = [
  {
    name: "1980 / 1970 Fowler Dr",
    why: "Bedbugs, cockroaches, mice; faulty wiring; abusive management",
    source: "Bed Bug Registry; RentItOrNot 'constant fight with management'"
  },
  {
    name: "2250 Homelands Dr (Starlight)",
    why: "ACORN tenant protest 2023; mice + cockroaches; elevator breakdowns; STRANGERS in hallways",
    source: "INsauga / CBC documentation"
  },
  {
    name: "240 Markland Drive (Renaissance)",
    why: "CBC: 'culture of fear and intimidation' during multi-year construction; power/water/elevator outages",
    source: "CBC News 2023"
  },
  {
    name: "Skyrise Rentals (2550 Eglinton W)",
    why: "NO PETS confirmed",
    source: "Zumper listing"
  },
  {
    name: "18 Reid Dr",
    why: "NO PETS",
    source: "Zumper listing"
  }
];

// Running zone polygons / markers
const RUNNING = [
  { name: "Sawmill Valley + Culham + UTM Loop", lat: 43.5582, lng: -79.6694, type: "trail-3season", note: "8.2 mi, 1 road crossing, NO winter maintenance, unlit" },
  { name: "Riverwood Yellow+Red Loop", lat: 43.5780, lng: -79.7000, type: "trail-3season", note: "1,578 AllTrails reviews — most-reviewed Mississauga trail" },
  { name: "Martin Goodman Trail (Humber Bay → DT)", lat: 43.6210, lng: -79.4810, type: "trail-allyear", note: "ONLY year-round cleared trail in west GTA" },
  { name: "Mississauga Waterfront Trail", lat: 43.5530, lng: -79.6010, type: "trail-3season", note: "16.9 km continuous, NOT winter maintained" },
  { name: "Rattray Marsh (no bikes!)", lat: 43.5155, lng: -79.6300, type: "trail-3season", note: "CVC bans bikes — runner+dog friendly" },
  { name: "Centennial Park + Etobicoke Creek", lat: 43.6505, lng: -79.5870, type: "trail-3season", note: "Markland Wood golf breaks creek continuity, no clean 20km" },
  { name: "Burnhamthorpe Trail (winter spine)", lat: 43.5923, lng: -79.6420, type: "trail-allyear", note: "11 km paved, winter-maintained" },
];
